yml.name: TestNameFromFileProperties-yml
spring:
  datasource:
    url: jdbc:postgresql://localhost:40554/postgres
    username: admin
    password: qQ111111
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
#    properties.hibernate.format_sql: true